version: '3.7'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stormsafe
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - stormsafe-network
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stormsafe
    networks:
      - stormsafe-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  stormsafe-network:
    driver: bridge

volumes:
  postgres-data:
