version: '3.8'

services:
  stormsafe-api:
    build: .
    container_name: stormsafe-api
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=segredo123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=120206
      - APP_USER=RM556652
      - APP_USER_PASSWORD=120206
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "ls"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  oracle_data:
